name: Hello Script Test

on:
  push:
    branches: [ "main" ]

jobs:
  run-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x ./hello.sh

      - name: Run script
        run: ./hello.sh
